/* eslint-disable */
/**
 * accident-manager-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DischargeTypeEnum } from './discharge-type-enum'

/**
 *
 * @export
 * @interface AddEventInput
 */
export interface AddEventInput {
  /**
   * 情景ID scene id
   * @type {string}
   * @memberof AddEventInput
   */
  sceneId?: string
  /**
   * 事件名称 event name
   * @type {string}
   * @memberof AddEventInput
   */
  name?: string | null
  /**
   *
   * @type {DischargeTypeEnum}
   * @memberof AddEventInput
   */
  dischargeType?: DischargeTypeEnum
  /**
   * 事件开始时间 event start time
   * @type {string}
   * @memberof AddEventInput
   */
  startTime?: string
  /**
   * 事件结束时间 event end time
   * @type {string}
   * @memberof AddEventInput
   */
  endTime?: string
  /**
   * 流量 discharge
   * @type {number}
   * @memberof AddEventInput
   */
  discharge?: number
  /**
   * 流量时间序列ID discharge time series id
   * @type {string}
   * @memberof AddEventInput
   */
  dischargeTS?: string | null
  /**
   * 事件地点 event location
   * @type {string}
   * @memberof AddEventInput
   */
  location?: string | null
  /**
   * 事件备注 event remark
   * @type {string}
   * @memberof AddEventInput
   */
  remark?: string | null
  /**
   * 事件类型 event type
   * @type {string}
   * @memberof AddEventInput
   */
  eventType?: string | null
}
