/* eslint-disable */
/**
 * accident-manager-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ValueInfo } from './value-info'

/**
 *
 * @export
 * @interface ComponentDetailInput
 */
export interface ComponentDetailInput {
  /**
   * 污染物代码 pollutant code
   * @type {string}
   * @memberof ComponentDetailInput
   */
  code?: string | null
  /**
   * 污染物名称 pollutant name
   * @type {string}
   * @memberof ComponentDetailInput
   */
  name?: string | null
  /**
   * 污染物备注 pollutant remark
   * @type {string}
   * @memberof ComponentDetailInput
   */
  remark?: string | null
  /**
   * 事件ID event id
   * @type {string}
   * @memberof ComponentDetailInput
   */
  eventId?: string
  /**
   * 污染物属性 pollutant attributes
   * @type {Array<ValueInfo>}
   * @memberof ComponentDetailInput
   */
  values?: Array<ValueInfo> | null
}
