/* eslint-disable */
/**
 * accident-manager-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 0-TimeSeries(time series) 1-Constant(constant)
 * @export
 * @enum {string}
 */

export const DischargeTypeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const

export type DischargeTypeEnum = (typeof DischargeTypeEnum)[keyof typeof DischargeTypeEnum]
