/* eslint-disable */
/**
 * accident-manager-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EventDetailInput } from './event-detail-input'

/**
 *
 * @export
 * @interface SceneDetailInput
 */
export interface SceneDetailInput {
  /**
   * 情景名称 scene name
   * @type {string}
   * @memberof SceneDetailInput
   */
  name?: string | null
  /**
   * 对应的方案ID corresponding scenario id
   * @type {string}
   * @memberof SceneDetailInput
   */
  scenarioId?: string | null
  /**
   * 数据源 data source
   * @type {string}
   * @memberof SceneDetailInput
   */
  dataSource?: string | null
  /**
   * 操作人员 operator
   * @type {string}
   * @memberof SceneDetailInput
   */
  operator?: string | null
  /**
   * 操作时间 operate time
   * @type {string}
   * @memberof SceneDetailInput
   */
  operateTime?: string
  /**
   * 情景备注 scene remark
   * @type {string}
   * @memberof SceneDetailInput
   */
  remark?: string | null
  /**
   * 情景下的事件信息 subordinate events
   * @type {Array<EventDetailInput>}
   * @memberof SceneDetailInput
   */
  events?: Array<EventDetailInput> | null
}
