/* tslint:disable */
/* eslint-disable */
/**
 * 数据中台服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 创建/更新数据样本集DTO
 * @export
 * @interface CreateUpdateDataSampleSetDto
 */
export interface CreateUpdateDataSampleSetDto {
  /**
   * 样本名称
   * @type {string}
   * @memberof CreateUpdateDataSampleSetDto
   */
  name?: string | null
  /**
   * 代码
   * @type {string}
   * @memberof CreateUpdateDataSampleSetDto
   */
  code?: string | null
  /**
   * 实际存储的指标列表
   * @type {Array<string>}
   * @memberof CreateUpdateDataSampleSetDto
   */
  indicators?: Array<string> | null
  /**
   * 开始时间
   * @type {string}
   * @memberof CreateUpdateDataSampleSetDto
   */
  startTime?: string
  /**
   * 结束时间
   * @type {string}
   * @memberof CreateUpdateDataSampleSetDto
   */
  endTime?: string
  /**
   * 配置表的Id
   * @type {string}
   * @memberof CreateUpdateDataSampleSetDto
   */
  configId?: string
  /**
   * MinIO上数据路径
   * @type {string}
   * @memberof CreateUpdateDataSampleSetDto
   */
  dataUri?: string | null
  /**
   * 状态
   * @type {number}
   * @memberof CreateUpdateDataSampleSetDto
   */
  status?: number
}
