/* eslint-disable */
/**
 * 数据中台服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DataCleanTagConfigOutput } from './data-clean-tag-config-output'

/**
 *
 * @export
 * @interface DataCleanTagConfigOutputPage
 */
export interface DataCleanTagConfigOutputPage {
  /**
   *
   * @type {number}
   * @memberof DataCleanTagConfigOutputPage
   */
  pageIndex?: number
  /**
   *
   * @type {number}
   * @memberof DataCleanTagConfigOutputPage
   */
  pageSize?: number
  /**
   *
   * @type {Array<DataCleanTagConfigOutput>}
   * @memberof DataCleanTagConfigOutputPage
   */
  list?: Array<DataCleanTagConfigOutput> | null
  /**
   *
   * @type {number}
   * @memberof DataCleanTagConfigOutputPage
   */
  totalCount?: number
  /**
   *
   * @type {number}
   * @memberof DataCleanTagConfigOutputPage
   */
  totalPages?: number
  /**
   *
   * @type {boolean}
   * @memberof DataCleanTagConfigOutputPage
   */
  haveNextPage?: boolean
}
