/* eslint-disable */
/**
 * 数据中台服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReferenceIndicatorsConfigOutput
 */
export interface ReferenceIndicatorsConfigOutput {
  /**
   * 指标ID
   * @type {string}
   * @memberof ReferenceIndicatorsConfigOutput
   */
  indicatorConfigId?: string
  /**
   * 参考指标ID
   * @type {string}
   * @memberof ReferenceIndicatorsConfigOutput
   */
  referenceIndicatorId?: string
}
