/* eslint-disable */
/**
 * digital-twin-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { StringStringKeyValue } from './string-string-key-value'

/**
 *
 * @export
 * @interface AddKeyPointInput
 */
export interface AddKeyPointInput {
  /**
   * 重要点位显示名称 key point show name
   * @type {string}
   * @memberof AddKeyPointInput
   */
  showName?: string | null
  /**
   * 重要点位与模型点位映射关系ID列表 mapping relation ids between key point and model point
   * @type {Array<string>}
   * @memberof AddKeyPointInput
   */
  keyPointDetails?: Array<string> | null
  /**
   * 重要点位属性 key point attributes
   * @type {Array<StringStringKeyValue>}
   * @memberof AddKeyPointInput
   */
  attributes?: Array<StringStringKeyValue> | null
}
