/* eslint-disable */
/**
 * wwtp-paas-main-bus-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PercentagesDto } from './percentages-dto'

/**
 * 模型精度数据
 * @export
 * @interface ModelPrecision
 */
export interface ModelPrecision {
  /**
   * 指标 indicator code
   * @type {string}
   * @memberof ModelPrecision
   */
  code?: string | null
  /**
   * 单位 unit
   * @type {string}
   * @memberof ModelPrecision
   */
  unit?: string | null
  /**
   * 总体评价 overall evaluation
   * @type {string}
   * @memberof ModelPrecision
   */
  evaluation?: string | null
  /**
   * 评价Code
   * @type {string}
   * @memberof ModelPrecision
   */
  levelCode?: string | null
  /**
   * 精度百分比区间占比 precision region detailed data
   * @type {Array<PercentagesDto>}
   * @memberof ModelPrecision
   */
  percentagesDistri?: Array<PercentagesDto> | null
}
