/* eslint-disable */
/**
 * 污水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TsPair2
 */
export interface TsPair2 {
  /**
   * 时间 time
   * @type {string}
   * @memberof TsPair2
   */
  time?: string
  /**
   * 数值 value
   * @type {number}
   * @memberof TsPair2
   */
  value?: number
}
