/* eslint-disable */
/**
 * 供水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CurveTsInfo
 */
export interface CurveTsInfo {
  /**
   * 时间
   * @type {Array<number>}
   * @memberof CurveTsInfo
   */
  t?: Array<number> | null
  /**
   *
   * @type {Array<number>}
   * @memberof CurveTsInfo
   */
  v?: Array<number> | null
  /**
   * 模型点位
   * @type {string}
   * @memberof CurveTsInfo
   */
  modelFeatureId?: string | null
  /**
   * 数据ID
   * @type {string}
   * @memberof CurveTsInfo
   */
  id?: string | null
  /**
   * 指标Id
   * @type {string}
   * @memberof CurveTsInfo
   */
  indicatorId?: string | null
}
