/* eslint-disable */
/**
 * 供水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ComponentDetailInfo } from './component-detail-info'
// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null'

/**
 * 事件信息
 * @export
 * @interface EventDetailInfo
 */
export interface EventDetailInfo {
  /**
   *
   * @type {string}
   * @memberof EventDetailInfo
   */
  id?: string
  /**
   * 情景id
   * @type {string}
   * @memberof EventDetailInfo
   */
  sceneId?: string
  /**
   * 事件名
   * @type {string}
   * @memberof EventDetailInfo
   */
  name?: string | null
  /**
   * 0-TimeSeries(时间序列) 1-Constant(常量)
   * @type {number}
   * @memberof EventDetailInfo
   */
  dischargeType?: EventDetailInfoDischargeTypeEnum
  /**
   * 开始时间
   * @type {string}
   * @memberof EventDetailInfo
   */
  startTime?: string
  /**
   * 结束时间
   * @type {string}
   * @memberof EventDetailInfo
   */
  endTime?: string
  /**
   * 事件位置，对于爆管事件和水质事件，填模型id
   * @type {string}
   * @memberof EventDetailInfo
   */
  location?: string | null
  /**
   *
   * @type {string}
   * @memberof EventDetailInfo
   */
  riverID?: string | null
  /**
   *
   * @type {number}
   * @memberof EventDetailInfo
   */
  chainage?: number | null
  /**
   * 排水量/泄水量
   * @type {Null}
   * @memberof EventDetailInfo
   */
  dischargeValue?: Null
  /**
   * 事件类型
   * @type {string}
   * @memberof EventDetailInfo
   */
  eventType?: string | null
  /**
   * 污染物（污染物事故使用）
   * @type {Array<ComponentDetailInfo>}
   * @memberof EventDetailInfo
   */
  components?: Array<ComponentDetailInfo> | null
}

export const EventDetailInfoDischargeTypeEnum = {
  '0': 0 as number,
  '1': 1 as number,
} as const

export type EventDetailInfoDischargeTypeEnum =
  (typeof EventDetailInfoDischargeTypeEnum)[keyof typeof EventDetailInfoDischargeTypeEnum]
