/* eslint-disable */
/**
 * wd-domain-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PointDataTypeInfo
 */
export interface PointDataTypeInfo {
  /**
   *
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  id?: string | null
  /**
   *
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  tenantId?: string | null
  /**
   * ModelPoint表id
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  modelPointId?: string
  /**
   *
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  modelComponent?: string | null
  /**
   * 指标表id
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  deviceIndicatorId?: string
  /**
   * 数据类型
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  modelDataType?: string | null
  /**
   * 模板id
   * @type {string}
   * @memberof PointDataTypeInfo
   */
  templateId?: string
}
