/* eslint-disable */
/**
 * 供水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryPatternListInput
 */
export interface QueryPatternListInput {
  /**
   *
   * @type {string}
   * @memberof QueryPatternListInput
   */
  scenarioId: string
  /**
   *
   * @type {Array<number>}
   * @memberof QueryPatternListInput
   */
  itemTypes: Array<QueryPatternListInputItemTypesEnum>
}

export const QueryPatternListInputItemTypesEnum = {
  '0': 0 as number,
  '1': 1 as number,
  '2': 2 as number,
  '3': 3 as number,
  '4': 4 as number,
} as const

export type QueryPatternListInputItemTypesEnum =
  (typeof QueryPatternListInputItemTypesEnum)[keyof typeof QueryPatternListInputItemTypesEnum]
