/* eslint-disable */
/**
 * 供水业务中台领域服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ControlTsInfo } from './control-ts-info'

/**
 *
 * @export
 * @interface UpdateControlTsInput
 */
export interface UpdateControlTsInput {
  /**
   * 方案Id
   * @type {string}
   * @memberof UpdateControlTsInput
   */
  scenarioId: string
  /**
   * 修改的数据
   * @type {Array<ControlTsInfo>}
   * @memberof UpdateControlTsInput
   */
  data: Array<ControlTsInfo>
}
