/* eslint-disable */
/**
 * wd-domain-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null'

/**
 * 事件
 * @export
 * @interface WdEventDetailInput
 */
export interface WdEventDetailInput {
  /**
   * 0-PipeBurst(爆管) 1-CloseValve(关阀) 2-WQAccident(水质事件)
   * @type {number}
   * @memberof WdEventDetailInput
   */
  eventType?: WdEventDetailInputEventTypeEnum
  /**
   * 开始时间
   * @type {string}
   * @memberof WdEventDetailInput
   */
  startTime?: string
  /**
   * 结束时间
   * @type {string}
   * @memberof WdEventDetailInput
   */
  endTime?: string
  /**
   * 事件位置，对于爆管事件和水质事件，填模型id
   * @type {string}
   * @memberof WdEventDetailInput
   */
  location?: string | null
  /**
   * 排水量/泄水量
   * @type {Null}
   * @memberof WdEventDetailInput
   */
  dischargeValue?: Null
}

export const WdEventDetailInputEventTypeEnum = {
  '0': 0 as number,
  '1': 1 as number,
  '2': 2 as number,
} as const

export type WdEventDetailInputEventTypeEnum =
  (typeof WdEventDetailInputEventTypeEnum)[keyof typeof WdEventDetailInputEventTypeEnum]
