/* eslint-disable */
/**
 * 污水业务中台基础服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AlarmLogInout
 */
export interface AlarmLogInout {
  /**
   *
   * @type {string}
   * @memberof AlarmLogInout
   */
  id?: string
  /**
   * 产生报警数据的时间 alarm data generation time
   * @type {string}
   * @memberof AlarmLogInout
   */
  alarmTime?: string
  /**
   * 报警时间 alarm time
   * @type {string}
   * @memberof AlarmLogInout
   */
  predictionTime?: string
  /**
   * 点位类型 point type
   * @type {number}
   * @memberof AlarmLogInout
   */
  pointType?: number
  /**
   * 扩展信息，生化池 extend information for biochemical pool index
   * @type {string}
   * @memberof AlarmLogInout
   */
  extInfo?: string | null
  /**
   * 指标 indicator
   * @type {string}
   * @memberof AlarmLogInout
   */
  indicator?: string | null
  /**
   * 点位名称 point name
   * @type {string}
   * @memberof AlarmLogInout
   */
  pointName?: string | null
  /**
   * 点位代码 point code
   * @type {string}
   * @memberof AlarmLogInout
   */
  nodeCode?: string | null
  /**
   * 报警等级 alarm grade
   * @type {number}
   * @memberof AlarmLogInout
   */
  grade?: number
  /**
   * 数值 value
   * @type {number}
   * @memberof AlarmLogInout
   */
  value?: number
  /**
   * 报警信息 alarm message
   * @type {string}
   * @memberof AlarmLogInout
   */
  message?: string | null
  /**
   * 报警类型 alarm type
   * @type {number}
   * @memberof AlarmLogInout
   */
  alarmType?: AlarmLogInoutAlarmTypeEnum
}

export const AlarmLogInoutAlarmTypeEnum = {
  '0': 0 as number,
  '1': 1 as number,
  '2': 2 as number,
} as const

export type AlarmLogInoutAlarmTypeEnum =
  (typeof AlarmLogInoutAlarmTypeEnum)[keyof typeof AlarmLogInoutAlarmTypeEnum]
