/* eslint-disable */
/**
 * wwtp-paas-infrastructure-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DataCleanTagConfigOutput
 */
export interface DataCleanTagConfigOutput {
  /**
   * 配置ID config id
   * @type {string}
   * @memberof DataCleanTagConfigOutput
   */
  id?: string
  /**
   * 标签 data clean tag
   * @type {string}
   * @memberof DataCleanTagConfigOutput
   */
  tag?: string | null
  /**
   * 状态信息 device status
   * @type {string}
   * @memberof DataCleanTagConfigOutput
   */
  status?: string | null
  /**
   * 维护预警 device maintenance
   * @type {string}
   * @memberof DataCleanTagConfigOutput
   */
  message?: string | null
  /**
   * 是否正常 if the device is health
   * @type {boolean}
   * @memberof DataCleanTagConfigOutput
   */
  health?: boolean
  /**
   * 状态标识 status label
   * @type {string}
   * @memberof DataCleanTagConfigOutput
   */
  label?: string | null
  /**
   * 是否默认 if it is a default tag
   * @type {boolean}
   * @memberof DataCleanTagConfigOutput
   */
  default?: boolean
  /**
   *
   * @type {number}
   * @memberof DataCleanTagConfigOutput
   */
  grade?: DataCleanTagConfigOutputGradeEnum
}

export const DataCleanTagConfigOutputGradeEnum = {
  0: 0 as number,
  1: 1 as number,
  2: 2 as number,
} as const

export type DataCleanTagConfigOutputGradeEnum =
  (typeof DataCleanTagConfigOutputGradeEnum)[keyof typeof DataCleanTagConfigOutputGradeEnum]
