/* eslint-disable */
/**
 * wwtp-paas-infrastructure-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetAssemblyConfigInput
 */
export interface GetAssemblyConfigInput {
  /**
   * 点位类型编码
   * @type {string}
   * @memberof GetAssemblyConfigInput
   */
  pointTypeCode?: string | null
  /**
   * 点位类型 point type
   * @type {string}
   * @memberof GetAssemblyConfigInput
   */
  pointType?: string | null
  /**
   * 模板模型名称（即模板方案名称） template model name
   * @type {string}
   * @memberof GetAssemblyConfigInput
   */
  modelName: string
  /**
   * 点位编码 codes
   * @type {Array<string>}
   * @memberof GetAssemblyConfigInput
   */
  codes?: Array<string> | null
  /**
   * 是否在线点位 if it is an online point
   * @type {boolean}
   * @memberof GetAssemblyConfigInput
   */
  isInputPoint?: boolean | null
  /**
   * 扩展信息，生化池序号 extend information for biochemical pool index
   * @type {string}
   * @memberof GetAssemblyConfigInput
   */
  extInfo?: string | null
  /**
   * 生产线 product line
   * @type {string}
   * @memberof GetAssemblyConfigInput
   */
  productLine?: string | null
}
