/* eslint-disable */
/**
 * scenario-compute-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DhiDssScenarioComputeDaprServicesDtosPointExpressItem
 */
export interface DhiDssScenarioComputeDaprServicesDtosPointExpressItem {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof DhiDssScenarioComputeDaprServicesDtosPointExpressItem
   */
  pointParameterDic?: { [key: string]: string } | null
  /**
   *
   * @type {string}
   * @memberof DhiDssScenarioComputeDaprServicesDtosPointExpressItem
   */
  expression?: string | null
}
