/* eslint-disable */
/**
 * 模型配置服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
  /**
   * 是否分块，默认分块 whether to chunk
   * @type {string}
   * @memberof InlineObject
   */
  Chunked?: string
  /**
   * 分块序号 chunk number
   * @type {number}
   * @memberof InlineObject
   */
  Chunk?: number
  /**
   * 总的分块个数 total chunk numbers
   * @type {number}
   * @memberof InlineObject
   */
  TotalChunks?: number
  /**
   * 总的文件大小 file size
   * @type {number}
   * @memberof InlineObject
   */
  TotalSize?: number
  /**
   * 文件ID，同一个文件的所有文件块具有相同的ID file id, all the chunks of one file should have a same identifer
   * @type {string}
   * @memberof InlineObject
   */
  Identifer?: string
  /**
   * 文件名称 file name
   * @type {string}
   * @memberof InlineObject
   */
  FileName?: string
}
