/* eslint-disable */
/**
 * 模型配置服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OnlineIndicatorsItem
 */
export interface OnlineIndicatorsItem {
  /**
   * 数据项 data item
   * @type {string}
   * @memberof OnlineIndicatorsItem
   */
  item?: string | null
  /**
   * 数据类型 data type
   * @type {string}
   * @memberof OnlineIndicatorsItem
   */
  type?: string | null
  /**
   * 数据单位 data unit
   * @type {string}
   * @memberof OnlineIndicatorsItem
   */
  unit?: string | null
  /**
   * 数据阈值最大值 max value
   * @type {number}
   * @memberof OnlineIndicatorsItem
   */
  maxValue?: number
  /**
   * 数据阈值最小值 min value
   * @type {number}
   * @memberof OnlineIndicatorsItem
   */
  minValue?: number
  /**
   * 自定义阈值配置的json字符串，可替代MaxValue和MinValue custom data threshold in json format, MaxValue and MinValue will be replaced
   * @type {string}
   * @memberof OnlineIndicatorsItem
   */
  customJson?: string | null
}
