/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddMicroServiceInput
 */
export interface AddMicroServiceInput {
  /**
   * 微服务标识 micro service key
   * @type {string}
   * @memberof AddMicroServiceInput
   */
  serviceKey: string
  /**
   * 微服务名称 micro service name
   * @type {string}
   * @memberof AddMicroServiceInput
   */
  serviceName: string
  /**
   * 开发语言 develop language
   * @type {string}
   * @memberof AddMicroServiceInput
   */
  developVoice?: string | null
  /**
   * 是否需要网关鉴权 if require gateway authentication
   * @type {boolean}
   * @memberof AddMicroServiceInput
   */
  isGatewayAuth?: boolean
  /**
   * 负责人 micro service manager
   * @type {string}
   * @memberof AddMicroServiceInput
   */
  managerName?: string | null
  /**
   * 备注 remarks
   * @type {string}
   * @memberof AddMicroServiceInput
   */
  remarks?: string | null
}
