/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddButtonPerInput
 */
export interface AddButtonPerInput {
  /**
   * 父级菜单Id parent menu id
   * @type {string}
   * @memberof AddButtonPerInput
   */
  pid: string
  /**
   * 按钮名称 button name
   * @type {string}
   * @memberof AddButtonPerInput
   */
  name: string
  /**
   * 按钮权限规则-正则 button permission regular
   * @type {string}
   * @memberof AddButtonPerInput
   */
  regular?: string | null
  /**
   * 所属系统Id system id
   * @type {string}
   * @memberof AddButtonPerInput
   */
  systemId?: string | null
  /**
   * 所属系统Id function id
   * @type {string}
   * @memberof AddButtonPerInput
   */
  functionId?: string | null
  /**
   * 后端API权限规则
   * @type {string}
   * @memberof AddButtonPerInput
   */
  apiRegular?: string | null
}
