/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ButtonPerUnderMenuInput
 */
export interface ButtonPerUnderMenuInput {
  /**
   * 菜单下的按钮权限 button permission ids
   * @type {Array<string>}
   * @memberof ButtonPerUnderMenuInput
   */
  menuIds?: Array<string> | null
}
