/* eslint-disable */
/**
 * identity-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GrantPerInput
 */
export interface GrantPerInput {
  /**
   * 当前操作的角色ID role id
   * @type {string}
   * @memberof GrantPerInput
   */
  roleId: string
  /**
   * 要为角色赋予的菜单/按钮权限 menu/button permissions granted for the role
   * @type {Array<string>}
   * @memberof GrantPerInput
   */
  perIds?: Array<string> | null
}
