/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ModelNodeConfigInputOutput
 */
export interface ModelNodeConfigInputOutput {
  /**
   *
   * @type {string}
   * @memberof ModelNodeConfigInputOutput
   */
  nodeCode?: string | null
  /**
   *
   * @type {string}
   * @memberof ModelNodeConfigInputOutput
   */
  nodeName?: string | null
  /**
   *
   * @type {string}
   * @memberof ModelNodeConfigInputOutput
   */
  unit?: string | null
  /**
   *
   * @type {string}
   * @memberof ModelNodeConfigInputOutput
   */
  dataType?: string | null
}
