/* eslint-disable */
/**
 * identity-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryByConditionInput
 */
export interface QueryByConditionInput {
  /**
   * 开始时间 start time
   * @type {string}
   * @memberof QueryByConditionInput
   */
  startTime?: string
  /**
   * 结束时间 end time
   * @type {string}
   * @memberof QueryByConditionInput
   */
  endTime?: string
  /**
   * 在线点位代码列表 online point code list
   * @type {Array<string>}
   * @memberof QueryByConditionInput
   */
  onlineCodes?: Array<string> | null
  /**
   * 模型节点代码列表 model node code list
   * @type {Array<string>}
   * @memberof QueryByConditionInput
   */
  modelCodes?: Array<string> | null
}
