/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { QuerySuperUsersOutput } from './query-super-users-output'

/**
 *
 * @export
 * @interface QuerySuperUsersOutputPage
 */
export interface QuerySuperUsersOutputPage {
  /**
   *
   * @type {number}
   * @memberof QuerySuperUsersOutputPage
   */
  pageIndex?: number
  /**
   *
   * @type {number}
   * @memberof QuerySuperUsersOutputPage
   */
  pageSize?: number
  /**
   *
   * @type {Array<QuerySuperUsersOutput>}
   * @memberof QuerySuperUsersOutputPage
   */
  list?: Array<QuerySuperUsersOutput> | null
  /**
   *
   * @type {number}
   * @memberof QuerySuperUsersOutputPage
   */
  totalCount?: number
  /**
   *
   * @type {number}
   * @memberof QuerySuperUsersOutputPage
   */
  totalPages?: number
  /**
   *
   * @type {boolean}
   * @memberof QuerySuperUsersOutputPage
   */
  haveNextPage?: boolean
}
