/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TenantInfo
 */
export interface TenantInfo {
  /**
   * 租户ID tenant id
   * @type {string}
   * @memberof TenantInfo
   */
  tenantId?: string
  /**
   * 租户名称 tenant name
   * @type {string}
   * @memberof TenantInfo
   */
  tenantName?: string | null
}
