/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ToxicityInput
 */
export interface ToxicityInput {
  /**
   * 开始时间 start time
   * @type {string}
   * @memberof ToxicityInput
   */
  startTime?: string
  /**
   * 结束时间 end time
   * @type {string}
   * @memberof ToxicityInput
   */
  endTime?: string
  /**
   * 毒性仪位置 toxicity meter location
   * @type {string}
   * @memberof ToxicityInput
   */
  location?: string | null
  /**
   * 进水点 inlet
   * @type {string}
   * @memberof ToxicityInput
   */
  inlet?: string | null
}
