/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DhiTerminal } from './dhi-terminal'
// May contain unused imports in some cases
// @ts-ignore
import { RoleInfo } from './role-info'

/**
 *
 * @export
 * @interface UserInfoWithStatus
 */
export interface UserInfoWithStatus {
  /**
   *
   * @type {string}
   * @memberof UserInfoWithStatus
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof UserInfoWithStatus
   */
  userName?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfoWithStatus
   */
  surName?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfoWithStatus
   */
  phoneNumber?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfoWithStatus
   */
  email?: string | null
  /**
   *
   * @type {Array<RoleInfo>}
   * @memberof UserInfoWithStatus
   */
  roleInfos?: Array<RoleInfo> | null
  /**
   *
   * @type {Array<DhiTerminal>}
   * @memberof UserInfoWithStatus
   */
  dhiTerminal?: Array<DhiTerminal> | null
  /**
   *
   * @type {boolean}
   * @memberof UserInfoWithStatus
   */
  online?: boolean
}
