/* eslint-disable */
/**
 * 用户认证管理服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserMenuPer
 */
export interface UserMenuPer {
  /**
   * 权限ID permission id
   * @type {string}
   * @memberof UserMenuPer
   */
  id?: string
  /**
   * 菜单名称 menu name
   * @type {string}
   * @memberof UserMenuPer
   */
  name?: string | null
  /**
   * 菜单类型 menu type
   * @type {number}
   * @memberof UserMenuPer
   */
  menuType?: UserMenuPerMenuTypeEnum
  /**
   * 菜单路由,前端的路由走向 menu router
   * @type {string}
   * @memberof UserMenuPer
   */
  menuRouter?: string | null
}

export const UserMenuPerMenuTypeEnum = {
  '0': 0 as number,
  '1': 1 as number,
} as const

export type UserMenuPerMenuTypeEnum =
  (typeof UserMenuPerMenuTypeEnum)[keyof typeof UserMenuPerMenuTypeEnum]
