/* eslint-disable */
/**
 * model-information-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios'
import { Configuration } from '../configuration'
import { URL } from '../../sdk-helper'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base'
// @ts-ignore
import { AddJunctionInput } from '../models'
// @ts-ignore
import { DeleteInput } from '../models'
// @ts-ignore
import { QueryJunctionDto } from '../models'
// @ts-ignore
import { RemoteServiceErrorResponse } from '../models'
// @ts-ignore
import { UpdateJunctionInput } from '../models'
/**
 * WDJunctionApi - axios parameter creator
 * @export
 */
export const WDJunctionApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary 新增节点要素编辑信息 Add junction information
     * @param {AddJunctionInput} [addJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionAddPost: async (
      addJunctionInput?: AddJunctionInput,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/model-information/domain-wd/junction/add`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        addJunctionInput,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
     * @param {string} [scenarioId] 方案ID scenario id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionAllGet: async (
      scenarioId?: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/model-information/domain-wd/junction/all`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (scenarioId !== undefined) {
        localVarQueryParameter['scenarioId'] = scenarioId
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary 删除节点要素编辑信息 Delete junction information
     * @param {DeleteInput} [deleteInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionDeletePost: async (
      deleteInput?: DeleteInput,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/model-information/domain-wd/junction/delete`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        deleteInput,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
     * @param {string} [scenarioId] 方案ID scenario id
     * @param {Array<string>} [muids] 模型中节点ID列表 junction muids
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionListGet: async (
      scenarioId?: string,
      muids?: Array<string>,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/model-information/domain-wd/junction/list`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (scenarioId !== undefined) {
        localVarQueryParameter['scenarioId'] = scenarioId
      }

      if (muids !== undefined) {
        localVarQueryParameter['muids'] = muids
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
     * @param {AddJunctionInput} [addJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionResavePost: async (
      addJunctionInput?: AddJunctionInput,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/model-information/domain-wd/junction/resave`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        addJunctionInput,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary 修改节点要素信息 Update junction information
     * @param {UpdateJunctionInput} [updateJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionUpdatePost: async (
      updateJunctionInput?: UpdateJunctionInput,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/model-information/domain-wd/junction/update`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateJunctionInput,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * WDJunctionApi - functional programming interface
 * @export
 */
export const WDJunctionApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = WDJunctionApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary 新增节点要素编辑信息 Add junction information
     * @param {AddJunctionInput} [addJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ModelInformationDomainWdJunctionAddPost(
      addJunctionInput?: AddJunctionInput,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ModelInformationDomainWdJunctionAddPost(
          addJunctionInput,
          options,
        )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     *
     * @summary 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
     * @param {string} [scenarioId] 方案ID scenario id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ModelInformationDomainWdJunctionAllGet(
      scenarioId?: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QueryJunctionDto>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ModelInformationDomainWdJunctionAllGet(
          scenarioId,
          options,
        )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     *
     * @summary 删除节点要素编辑信息 Delete junction information
     * @param {DeleteInput} [deleteInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ModelInformationDomainWdJunctionDeletePost(
      deleteInput?: DeleteInput,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ModelInformationDomainWdJunctionDeletePost(
          deleteInput,
          options,
        )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     *
     * @summary 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
     * @param {string} [scenarioId] 方案ID scenario id
     * @param {Array<string>} [muids] 模型中节点ID列表 junction muids
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ModelInformationDomainWdJunctionListGet(
      scenarioId?: string,
      muids?: Array<string>,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QueryJunctionDto>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ModelInformationDomainWdJunctionListGet(
          scenarioId,
          muids,
          options,
        )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     *
     * @summary 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
     * @param {AddJunctionInput} [addJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ModelInformationDomainWdJunctionResavePost(
      addJunctionInput?: AddJunctionInput,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ModelInformationDomainWdJunctionResavePost(
          addJunctionInput,
          options,
        )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     *
     * @summary 修改节点要素信息 Update junction information
     * @param {UpdateJunctionInput} [updateJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1ModelInformationDomainWdJunctionUpdatePost(
      updateJunctionInput?: UpdateJunctionInput,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.apiV1ModelInformationDomainWdJunctionUpdatePost(
          updateJunctionInput,
          options,
        )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
  }
}

/**
 * WDJunctionApi - factory interface
 * @export
 */
export const WDJunctionApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = WDJunctionApiFp(configuration)
  return {
    /**
     *
     * @summary 新增节点要素编辑信息 Add junction information
     * @param {AddJunctionInput} [addJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionAddPost(
      addJunctionInput?: AddJunctionInput,
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .apiV1ModelInformationDomainWdJunctionAddPost(addJunctionInput, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
     * @param {string} [scenarioId] 方案ID scenario id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionAllGet(
      scenarioId?: string,
      options?: any,
    ): AxiosPromise<Array<QueryJunctionDto>> {
      return localVarFp
        .apiV1ModelInformationDomainWdJunctionAllGet(scenarioId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary 删除节点要素编辑信息 Delete junction information
     * @param {DeleteInput} [deleteInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionDeletePost(
      deleteInput?: DeleteInput,
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .apiV1ModelInformationDomainWdJunctionDeletePost(deleteInput, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
     * @param {string} [scenarioId] 方案ID scenario id
     * @param {Array<string>} [muids] 模型中节点ID列表 junction muids
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionListGet(
      scenarioId?: string,
      muids?: Array<string>,
      options?: any,
    ): AxiosPromise<Array<QueryJunctionDto>> {
      return localVarFp
        .apiV1ModelInformationDomainWdJunctionListGet(scenarioId, muids, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
     * @param {AddJunctionInput} [addJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionResavePost(
      addJunctionInput?: AddJunctionInput,
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .apiV1ModelInformationDomainWdJunctionResavePost(addJunctionInput, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary 修改节点要素信息 Update junction information
     * @param {UpdateJunctionInput} [updateJunctionInput]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1ModelInformationDomainWdJunctionUpdatePost(
      updateJunctionInput?: UpdateJunctionInput,
      options?: any,
    ): AxiosPromise<object> {
      return localVarFp
        .apiV1ModelInformationDomainWdJunctionUpdatePost(updateJunctionInput, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * WDJunctionApi - object-oriented interface
 * @export
 * @class WDJunctionApi
 * @extends {BaseAPI}
 */
export class WDJunctionApi extends BaseAPI {
  /**
   *
   * @summary 新增节点要素编辑信息 Add junction information
   * @param {AddJunctionInput} [addJunctionInput]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WDJunctionApi
   */
  public apiV1ModelInformationDomainWdJunctionAddPost(
    addJunctionInput?: AddJunctionInput,
    options?: AxiosRequestConfig,
  ) {
    return WDJunctionApiFp(this.configuration)
      .apiV1ModelInformationDomainWdJunctionAddPost(addJunctionInput, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary 获取该方案下所有的节点要素信息 Get all junctions information of a scenario
   * @param {string} [scenarioId] 方案ID scenario id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WDJunctionApi
   */
  public apiV1ModelInformationDomainWdJunctionAllGet(
    scenarioId?: string,
    options?: AxiosRequestConfig,
  ) {
    return WDJunctionApiFp(this.configuration)
      .apiV1ModelInformationDomainWdJunctionAllGet(scenarioId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary 删除节点要素编辑信息 Delete junction information
   * @param {DeleteInput} [deleteInput]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WDJunctionApi
   */
  public apiV1ModelInformationDomainWdJunctionDeletePost(
    deleteInput?: DeleteInput,
    options?: AxiosRequestConfig,
  ) {
    return WDJunctionApiFp(this.configuration)
      .apiV1ModelInformationDomainWdJunctionDeletePost(deleteInput, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary 获取该方案下指定muids的节点要素信息 Get junctions information of a scenario by muids
   * @param {string} [scenarioId] 方案ID scenario id
   * @param {Array<string>} [muids] 模型中节点ID列表 junction muids
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WDJunctionApi
   */
  public apiV1ModelInformationDomainWdJunctionListGet(
    scenarioId?: string,
    muids?: Array<string>,
    options?: AxiosRequestConfig,
  ) {
    return WDJunctionApiFp(this.configuration)
      .apiV1ModelInformationDomainWdJunctionListGet(scenarioId, muids, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary 保存节点要素信息，原有节点信息会被删除 Save junction information, old junction information will be deleted
   * @param {AddJunctionInput} [addJunctionInput]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WDJunctionApi
   */
  public apiV1ModelInformationDomainWdJunctionResavePost(
    addJunctionInput?: AddJunctionInput,
    options?: AxiosRequestConfig,
  ) {
    return WDJunctionApiFp(this.configuration)
      .apiV1ModelInformationDomainWdJunctionResavePost(addJunctionInput, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary 修改节点要素信息 Update junction information
   * @param {UpdateJunctionInput} [updateJunctionInput]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WDJunctionApi
   */
  public apiV1ModelInformationDomainWdJunctionUpdatePost(
    updateJunctionInput?: UpdateJunctionInput,
    options?: AxiosRequestConfig,
  ) {
    return WDJunctionApiFp(this.configuration)
      .apiV1ModelInformationDomainWdJunctionUpdatePost(updateJunctionInput, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
