/* eslint-disable */
/**
 * 文件服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 获取文件下载路径输出Dto
 * @export
 * @interface QueryFileDownloadPathsOutput
 */
export interface QueryFileDownloadPathsOutput {
  /**
   * 文件对象名称，需要带扩展名,如:/images/device/t3-阀门_3a02c468-a8be-699c-e274-692bbfb9879b.png
   * @type {string}
   * @memberof QueryFileDownloadPathsOutput
   */
  objectName?: string | null
  /**
   * 文件路径
   * @type {string}
   * @memberof QueryFileDownloadPathsOutput
   */
  filePath?: string | null
}
