/* eslint-disable */
/**
 * scenario-manager-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeleteScenarioGroupPara
 */
export interface DeleteScenarioGroupPara {
  /**
   * 方案组ID scenario\'s group Id
   * @type {string}
   * @memberof DeleteScenarioGroupPara
   */
  scenarioGroupId?: string | null
}
