/* eslint-disable */
/**
 * scenario-manager-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Group
 */
export interface Group {
  /**
   *
   * @type {string}
   * @memberof Group
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof Group
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof Group
   */
  parentId: string
  /**
   *
   * @type {number}
   * @memberof Group
   */
  groupType?: number
  /**
   *
   * @type {string}
   * @memberof Group
   */
  itemRef?: string | null
  /**
   *
   * @type {string}
   * @memberof Group
   */
  groupFamily: string
  /**
   *
   * @type {string}
   * @memberof Group
   */
  groupLevel: string
  /**
   *
   * @type {string}
   * @memberof Group
   */
  itemId?: string
  /**
   *
   * @type {string}
   * @memberof Group
   */
  version?: string
  /**
   *
   * @type {string}
   * @memberof Group
   */
  tenantId?: string | null
  /**
   *
   * @type {Group}
   * @memberof Group
   */
  parent?: Group
  /**
   *
   * @type {string}
   * @memberof Group
   */
  path?: string | null
}
