/* eslint-disable */
/**
 * identity-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MappingConfigInputOutput
 */
export interface MappingConfigInputOutput {
  /**
   * 点位ID
   * @type {string}
   * @memberof MappingConfigInputOutput
   */
  id?: string
  /**
   * 系统点位编码
   * @type {string}
   * @memberof MappingConfigInputOutput
   */
  pointCode?: string | null
  /**
   * 模型点位编码
   * @type {string}
   * @memberof MappingConfigInputOutput
   */
  modelNodeCode?: string | null
  /**
   * 系统点位ID
   * @type {string}
   * @memberof MappingConfigInputOutput
   */
  sysId?: string
  /**
   * 默认值
   * @type {number}
   * @memberof MappingConfigInputOutput
   */
  defaultValue?: number
  /**
   * 保留字段
   * @type {string}
   * @memberof MappingConfigInputOutput
   */
  reserve?: string | null
}
