/* eslint-disable */
/**
 * identity-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Scenario
 */
export interface Scenario {
  /**
   * 方案名称 scenario name
   * @type {string}
   * @memberof Scenario
   */
  scenarioName?: string | null
  /**
   * 参数值 parameter value
   * @type {number}
   * @memberof Scenario
   */
  value?: number
}
