/* eslint-disable */
/**
 * identity-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TenantBelongSystemDto
 */
export interface TenantBelongSystemDto {
  /**
   * 系统ID system id
   * @type {string}
   * @memberof TenantBelongSystemDto
   */
  systemId?: string
  /**
   * 系统名称 system name
   * @type {string}
   * @memberof TenantBelongSystemDto
   */
  systemName?: string | null
  /**
   * 租户ID tenant id
   * @type {string}
   * @memberof TenantBelongSystemDto
   */
  tenantId?: string
  /**
   * 租户名称 tenant name
   * @type {string}
   * @memberof TenantBelongSystemDto
   */
  tenantName?: string | null
}
