
/* eslint-disable */
/**
 * 模型计算服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EnumStatus } from './enum-status';

/**
 * 
 * @export
 * @interface ModelDriverDto
 */
export interface ModelDriverDto {
    /**
     * Id
     * @type {string}
     * @memberof ModelDriverDto
     */
    'id'?: string;
    /**
     * 项目名称
     * @type {string}
     * @memberof ModelDriverDto
     */
    'projectName'?: string | null;
    /**
     * 租户ID
     * @type {string}
     * @memberof ModelDriverDto
     */
    'tenantId'?: string;
    /**
     * 方案Id
     * @type {string}
     * @memberof ModelDriverDto
     */
    'scenarioId'?: string;
    /**
     * 模型类型
     * @type {string}
     * @memberof ModelDriverDto
     */
    'modelType'?: string | null;
    /**
     * 优先级
     * @type {number}
     * @memberof ModelDriverDto
     */
    'priority'?: number;
    /**
     * 模型信息
     * @type {string}
     * @memberof ModelDriverDto
     */
    'modelInfo'?: string | null;
    /**
     * 计算开始时间
     * @type {string}
     * @memberof ModelDriverDto
     */
    'computeBeginTime'?: string;
    /**
     * 计算结束时间
     * @type {string}
     * @memberof ModelDriverDto
     */
    'computeEndTime'?: string;
    /**
     * 计算节点
     * @type {string}
     * @memberof ModelDriverDto
     */
    'computeNode'?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof ModelDriverDto
     */
    'createTime'?: string;
    /**
     * 
     * @type {EnumStatus}
     * @memberof ModelDriverDto
     */
    'status'?: EnumStatus;
    /**
     * Todo
     * @type {number}
     * @memberof ModelDriverDto
     */
    'sequenceNumber'?: number;
    /**
     * 日志存储路径
     * @type {string}
     * @memberof ModelDriverDto
     */
    'logPath'?: string | null;
}

