
/* eslint-disable */
/**
 * 模型计算服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EnumStatus } from './enum-status';

/**
 * 更新计算状态
 * @export
 * @interface UpdateStatusInput
 */
export interface UpdateStatusInput {
    /**
     * 方案ID列表
     * @type {Array<string>}
     * @memberof UpdateStatusInput
     */
    'scenarioIds'?: Array<string> | null;
    /**
     * 
     * @type {EnumStatus}
     * @memberof UpdateStatusInput
     */
    'status'?: EnumStatus;
}

