/* eslint-disable */
/**
 * 模型编辑服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AddPipeDto } from './add-pipe-dto'

/**
 *
 * @export
 * @interface AddPipeInput
 */
export interface AddPipeInput {
  /**
   * 方案ID scenario id
   * @type {string}
   * @memberof AddPipeInput
   */
  scenarioId?: string | null
  /**
   * 新增管段列表 pipes to be added
   * @type {Array<AddPipeDto>}
   * @memberof AddPipeInput
   */
  pipes?: Array<AddPipeDto> | null
}
