/* eslint-disable */
/**
 * model-information-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateManualScenarioInput
 */
export interface CreateManualScenarioInput {
  /**
   * 方案名称 scenario name
   * @type {string}
   * @memberof CreateManualScenarioInput
   */
  newScenarioName?: string | null
  /**
   * 预报时刻 current time
   * @type {string}
   * @memberof CreateManualScenarioInput
   */
  currentTime?: string
  /**
   * 开始时刻 start time
   * @type {string}
   * @memberof CreateManualScenarioInput
   */
  startTime?: string
  /**
   * 结束时刻 end time
   * @type {string}
   * @memberof CreateManualScenarioInput
   */
  endTime?: string
  /**
   * 方案描述 scenario description
   * @type {string}
   * @memberof CreateManualScenarioInput
   */
  description?: string | null
}
