/* eslint-disable */
/**
 * 模型编辑服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeleteFlushingParaInput
 */
export interface DeleteFlushingParaInput {
  /**
   * 方案Id scenario id
   * @type {string}
   * @memberof DeleteFlushingParaInput
   */
  scenarioId: string
  /**
   * 管道冲洗参数ID pipe flushing parameter id
   * @type {string}
   * @memberof DeleteFlushingParaInput
   */
  id: string
}
