/* eslint-disable */
/**
 * 模型编辑服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OperateEnum } from './operate-enum'

/**
 *
 * @export
 * @interface QueryPipeDto
 */
export interface QueryPipeDto {
  /**
   * 模型中管段ID pipe muid
   * @type {string}
   * @memberof QueryPipeDto
   */
  muid?: string | null
  /**
   * 起始节点 from node
   * @type {string}
   * @memberof QueryPipeDto
   */
  fromNode?: string | null
  /**
   * 终止节点 to node
   * @type {string}
   * @memberof QueryPipeDto
   */
  toNode?: string | null
  /**
   * 管长 pipe length
   * @type {number}
   * @memberof QueryPipeDto
   */
  length?: number
  /**
   * 管径 pipe diameter
   * @type {number}
   * @memberof QueryPipeDto
   */
  diameter?: number
  /**
   * 管壁厚度 pipe wall thickness
   * @type {number}
   * @memberof QueryPipeDto
   */
  thickness?: number
  /**
   * 管道状态 pipe status
   * @type {number}
   * @memberof QueryPipeDto
   */
  pipeStatus?: number
  /**
   * 分区ID zone id
   * @type {string}
   * @memberof QueryPipeDto
   */
  zoneID?: string | null
  /**
   * 粗糙度 pipe roughness
   * @type {number}
   * @memberof QueryPipeDto
   */
  roughness?: number
  /**
   * 损失系数 loss coefficient
   * @type {number}
   * @memberof QueryPipeDto
   */
  lossCoeff?: number
  /**
   * 管材 pipe material
   * @type {string}
   * @memberof QueryPipeDto
   */
  material?: string | null
  /**
   * 建设时间 construction time
   * @type {string}
   * @memberof QueryPipeDto
   */
  constructionYear?: string
  /**
   * 描述 description
   * @type {string}
   * @memberof QueryPipeDto
   */
  description?: string | null
  /**
   * 数据源 data source
   * @type {string}
   * @memberof QueryPipeDto
   */
  dataSource?: string | null
  /**
   * 资产名称 asset name
   * @type {string}
   * @memberof QueryPipeDto
   */
  assetName?: string | null
  /**
   * 街道名称 street name
   * @type {string}
   * @memberof QueryPipeDto
   */
  streetName?: string | null
  /**
   * 起始节点坐标X coordinate x of from-node
   * @type {number}
   * @memberof QueryPipeDto
   */
  fromX?: number
  /**
   * 起始节点坐标Y coordinate y of from-node
   * @type {number}
   * @memberof QueryPipeDto
   */
  fromY?: number
  /**
   * 终止节点坐标X coordinate x of to-node
   * @type {number}
   * @memberof QueryPipeDto
   */
  toX?: number
  /**
   * 终止节点坐标Y coordinate y of to-node
   * @type {number}
   * @memberof QueryPipeDto
   */
  toY?: number
  /**
   *
   * @type {OperateEnum}
   * @memberof QueryPipeDto
   */
  operate?: OperateEnum
  /**
   * 管段ID pipe id
   * @type {string}
   * @memberof QueryPipeDto
   */
  id?: string
}
