/* eslint-disable */
/**
 * 模型编辑服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { InitialCondition } from './initial-condition'

/**
 *
 * @export
 * @interface UpdateInitialConditionInput
 */
export interface UpdateInitialConditionInput {
  /**
   * 热启动方案ID hotstart scenario id
   * @type {string}
   * @memberof UpdateInitialConditionInput
   */
  scenarioId?: string | null
  /**
   *
   * @type {InitialCondition}
   * @memberof UpdateInitialConditionInput
   */
  hotstartFiles?: InitialCondition
}
