/* eslint-disable */
/**
 * model-information-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateTankDto
 */
export interface UpdateTankDto {
  /**
   * 设备ID device id
   * @type {string}
   * @memberof UpdateTankDto
   */
  deviceId?: string
  /**
   * 模型中水池ID tank muid
   * @type {string}
   * @memberof UpdateTankDto
   */
  muid?: string | null
  /**
   * 底高程 base elevation
   * @type {number}
   * @memberof UpdateTankDto
   */
  elev?: number
  /**
   * 水头固定值 fixed HGL
   * @type {number}
   * @memberof UpdateTankDto
   */
  hgl?: number
  /**
   * 分区ID zone id
   * @type {string}
   * @memberof UpdateTankDto
   */
  zoneID?: string | null
  /**
   * 数据源 data source
   * @type {string}
   * @memberof UpdateTankDto
   */
  dataSource?: string | null
  /**
   * 描述 description
   * @type {string}
   * @memberof UpdateTankDto
   */
  description?: string | null
  /**
   * 水池水头类型 HGL level type
   * @type {number}
   * @memberof UpdateTankDto
   */
  wdTankHGLType?: number
  /**
   * 水头模式ID HGL pattern id
   * @type {string}
   * @memberof UpdateTankDto
   */
  patternID?: string | null
  /**
   * 水池混合的类型 tank mixing type
   * @type {number}
   * @memberof UpdateTankDto
   */
  wdTankMixing?: number
  /**
   * 初始污染物浓度 initial chemical concentration
   * @type {number}
   * @memberof UpdateTankDto
   */
  initQualityConcentration?: number
  /**
   * 降解系数 reaction coefficient
   * @type {number}
   * @memberof UpdateTankDto
   */
  reactionCoefficient?: number
  /**
   * 初始污染物占比 initial source percentage
   * @type {number}
   * @memberof UpdateTankDto
   */
  initQualityPercentage?: number
  /**
   * 初始水龄 initial water age
   * @type {number}
   * @memberof UpdateTankDto
   */
  iniQualityHour?: number
  /**
   * 污染物体积 component volume
   * @type {number}
   * @memberof UpdateTankDto
   */
  componentValue?: number
  /**
   * 坐标值 coordinate
   * @type {string}
   * @memberof UpdateTankDto
   */
  coorStr?: string | null
  /**
   * 创建时间 create time
   * @type {string}
   * @memberof UpdateTankDto
   */
  createTime?: string
  /**
   * 水池ID tank id
   * @type {string}
   * @memberof UpdateTankDto
   */
  id?: string
}
