/* eslint-disable */
/**
 * 方案计算服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput
 */
export interface DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput {
  /**
   * 模板方案的ID
   * @type {string}
   * @memberof DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput
   */
  parentScenarioId?: string
  /**
   * 调度方案名称
   * @type {string}
   * @memberof DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput
   */
  newScenarioName?: string | null
  /**
   * 开始时间
   * @type {string}
   * @memberof DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput
   */
  startTime?: string
  /**
   * 结束时间
   * @type {string}
   * @memberof DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput
   */
  endTime?: string
  /**
   * 方案描述
   * @type {string}
   * @memberof DhiDssScenarioComputeRfDtosCreateScheduleScenarioInput
   */
  description?: string | null
}
