/* tslint:disable */
/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FeedBackTarget } from './feed-back-target'

/**
 *
 * @export
 * @interface ControlCmdDeliveryLogDto
 */
export interface ControlCmdDeliveryLogDto {
  /**
   *
   * @type {string}
   * @memberof ControlCmdDeliveryLogDto
   */
  id?: string
  /**
   * 配置表id
   * @type {string}
   * @memberof ControlCmdDeliveryLogDto
   */
  configId?: string
  /**
   * 控制值
   * @type {number}
   * @memberof ControlCmdDeliveryLogDto
   */
  controlValue?: number
  /**
   * 创建时间
   * @type {string}
   * @memberof ControlCmdDeliveryLogDto
   */
  creationTime?: string
  /**
   * 更新时间
   * @type {string}
   * @memberof ControlCmdDeliveryLogDto
   */
  lastModificationTime?: string | null
  /**
   * 目标值
   * @type {Array<FeedBackTarget>}
   * @memberof ControlCmdDeliveryLogDto
   */
  feedBackTarget?: Array<FeedBackTarget> | null
  /**
   * 0-Delivering(开始下发) 1-Deliveried(已下发) 2-FailToDeliver(下发失败) 3-Executing(指令正在执行) 4-Fault(指令执行故障) 5-Failure(指令未被执行) 6-Success(指令执行完成) 7-SystemError(系统错误)
   * @type {number}
   * @memberof ControlCmdDeliveryLogDto
   */
  executeStatus?: ControlCmdDeliveryLogDtoExecuteStatusEnum
}

export const ControlCmdDeliveryLogDtoExecuteStatusEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
} as const

export type ControlCmdDeliveryLogDtoExecuteStatusEnum =
  (typeof ControlCmdDeliveryLogDtoExecuteStatusEnum)[keyof typeof ControlCmdDeliveryLogDtoExecuteStatusEnum]
