/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 设备指标
 * @export
 * @interface DeviceIndicator
 */
export interface DeviceIndicator {
  /**
   * 设备编码
   * @type {string}
   * @memberof DeviceIndicator
   */
  deviceCode?: string | null
  /**
   * 指标代码
   * @type {string}
   * @memberof DeviceIndicator
   */
  indicator?: string | null
}
