/* eslint-disable */
/**
 * iot-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GroupTreeOutput
 */
export interface GroupTreeOutput {
  /**
   * Id
   * @type {string}
   * @memberof GroupTreeOutput
   */
  id?: string
  /**
   * 分组名称
   * @type {string}
   * @memberof GroupTreeOutput
   */
  groupName?: string | null
  /**
   * 层级编码 如: 00010001
   * @type {string}
   * @memberof GroupTreeOutput
   */
  levelCode?: string | null
  /**
   * 父级层级编码 0001 可空,空代表顶级
   * @type {string}
   * @memberof GroupTreeOutput
   */
  parentLevelCode?: string | null
  /**
   * 资产或设备id，关联iot中的资产id或设备id
   * @type {Array<string>}
   * @memberof GroupTreeOutput
   */
  equipmentIds?: Array<string> | null
  /**
   *
   * @type {Array<GroupTreeOutput>}
   * @memberof GroupTreeOutput
   */
  children?: Array<GroupTreeOutput> | null
}
