/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * MqttBroker 信息
 * @export
 * @interface MqttBrokerInfo
 */
export interface MqttBrokerInfo {
  /**
   * 唯一标识，name
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  flag: string
  /**
   * Broker主机
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  host: string
  /**
   * 端口
   * @type {number}
   * @memberof MqttBrokerInfo
   */
  port: number
  /**
   * 客户端Id
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  clientId?: string | null
  /**
   * 用户名
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  userName: string
  /**
   * 密码
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  password: string
  /**
   * 0-None 1-ClientId 2-UserName 3-ClientIdAndUsername 4-ClientIdAndPassword 5-UsernameAndPassword 6-ClientIdAndUsernameAndPassword
   * @type {number}
   * @memberof MqttBrokerInfo
   */
  authenticationType?: MqttBrokerInfoAuthenticationTypeEnum
  /**
   * 是否启用, 默认不启用
   * @type {boolean}
   * @memberof MqttBrokerInfo
   */
  apply?: boolean
  /**
   * 数据Id
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  id?: string
  /**
   * 租户Id
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  tenantId?: string | null
  /**
   * 创建时间
   * @type {string}
   * @memberof MqttBrokerInfo
   */
  creationTime?: string
}

export const MqttBrokerInfoAuthenticationTypeEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const

export type MqttBrokerInfoAuthenticationTypeEnum =
  (typeof MqttBrokerInfoAuthenticationTypeEnum)[keyof typeof MqttBrokerInfoAuthenticationTypeEnum]
