/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReadNodeInput
 */
export interface ReadNodeInput {
  /**
   * opc server 标识 mark
   * @type {string}
   * @memberof ReadNodeInput
   */
  opcFlag: string
  /**
   * 节点 node
   * @type {string}
   * @memberof ReadNodeInput
   */
  node: string
  /**
   * 0-BoolValue 1-DateTimeValue 2-DblValue 3-LongValue 4-StrValue 5-FloatValue 6-UInt32Value 7-UInt16Value 8-Int32Value 9-Int16Value
   * @type {number}
   * @memberof ReadNodeInput
   */
  dataType: ReadNodeInputDataTypeEnum
}

export const ReadNodeInputDataTypeEnum = {
  '0': 0 as number,
  '1': 1 as number,
  '2': 2 as number,
  '3': 3 as number,
  '4': 4 as number,
  '5': 5 as number,
  '6': 6 as number,
  '7': 7 as number,
  '8': 8 as number,
  '9': 9 as number,
} as const

export type ReadNodeInputDataTypeEnum =
  (typeof ReadNodeInputDataTypeEnum)[keyof typeof ReadNodeInputDataTypeEnum]
