/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { LatestTimeSeries } from './latest-time-series'

/**
 * 保存实测数据
 * @export
 * @interface SaveRealTimeData
 */
export interface SaveRealTimeData {
  /**
   * 租户Id
   * @type {string}
   * @memberof SaveRealTimeData
   */
  tenantId?: string
  /**
   * 实时数据
   * @type {Array<LatestTimeSeries>}
   * @memberof SaveRealTimeData
   */
  values?: Array<LatestTimeSeries> | null
}
