/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MeasureDataInput } from './measure-data-input'

/**
 *
 * @export
 * @interface SaveTelemetryStructDataBatchInput
 */
export interface SaveTelemetryStructDataBatchInput {
  /**
   * 时间戳
   * @type {string}
   * @memberof SaveTelemetryStructDataBatchInput
   */
  ts?: string
  /**
   *
   * @type {Array<MeasureDataInput>}
   * @memberof SaveTelemetryStructDataBatchInput
   */
  values?: Array<MeasureDataInput> | null
}
