/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SearchIndicator
 */
export interface SearchIndicator {
  /**
   *
   * @type {boolean}
   * @memberof SearchIndicator
   */
  isSearchMeasure?: boolean
  /**
   *
   * @type {boolean}
   * @memberof SearchIndicator
   */
  isSearchSimul?: boolean
  /**
   *
   * @type {string}
   * @memberof SearchIndicator
   */
  indicator?: string | null
  /**
   *
   * @type {string}
   * @memberof SearchIndicator
   */
  label?: string | null
  /**
   *
   * @type {string}
   * @memberof SearchIndicator
   */
  showName?: string | null
  /**
   *
   * @type {string}
   * @memberof SearchIndicator
   */
  unit?: string | null
}
