/* eslint-disable */
/**
 * iot-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TimeseriesInput
 */
export interface TimeseriesInput {
  /**
   * 设备ID device id
   * @type {string}
   * @memberof TimeseriesInput
   */
  deviceId: string
  /**
   * 指标列表 indicators
   * @type {Array<string>}
   * @memberof TimeseriesInput
   */
  keys: Array<string>
  /**
   * 查询开始时间 start time
   * @type {string}
   * @memberof TimeseriesInput
   */
  startTs: string
  /**
   * 查询结束时间 end time
   * @type {string}
   * @memberof TimeseriesInput
   */
  endTs: string
  /**
   * 排序方式，ASC (升序)，DESC (降序) sort order, ASC (ASCENDING) or DESC (DESCENDING)
   * @type {string}
   * @memberof TimeseriesInput
   */
  orderBy?: string | null
}
