/* tslint:disable */
/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Tv
 */
export interface Tv {
  /**
   * 时间
   * @type {string}
   * @memberof Tv
   */
  t?: string | null
  /**
   * 数值
   * @type {string}
   * @memberof Tv
   */
  v?: string | null
}
