/* eslint-disable */
/**
 * IoT服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { StringStringKeyValue } from './string-string-key-value'

/**
 *
 * @export
 * @interface UpdateDeviceInput
 */
export interface UpdateDeviceInput {
  /**
   * 设备名称 device name
   * @type {string}
   * @memberof UpdateDeviceInput
   */
  name: string
  /**
   * 设备标签 device label
   * @type {string}
   * @memberof UpdateDeviceInput
   */
  label?: string | null
  /**
   * 设备描述 device description
   * @type {string}
   * @memberof UpdateDeviceInput
   */
  description?: string | null
  /**
   * 设备类型
   * @type {string}
   * @memberof UpdateDeviceInput
   */
  type?: string | null
  /**
   * 设备自定义属性 device customized attributes
   * @type {Array<StringStringKeyValue>}
   * @memberof UpdateDeviceInput
   */
  attributes?: Array<StringStringKeyValue> | null
  /**
   * 设备ID device Id
   * @type {string}
   * @memberof UpdateDeviceInput
   */
  id: string
}
